# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_on', 'title'), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='removed',
            field=models.BooleanField(default=False, help_text='If a post goes against the policy then it should be set as removed, rather than deleting it.', verbose_name='Removed'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts_post',
        ),
    ]
